
package edu.pantry.Pantry_WebServices_JAX_WS_Client_1.pantry_webservices_jax_ws_server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeHelloWorld", targetNamespace = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/", className = "edu.pantry.pantry_webservices_jax_ws_server.MakeHelloWorld")
    @ResponseWrapper(localName = "makeHelloWorldResponse", targetNamespace = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/", className = "edu.pantry.pantry_webservices_jax_ws_server.MakeHelloWorldResponse")
    @Action(input = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/HelloWorldService/makeHelloWorldRequest", output = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/HelloWorldService/makeHelloWorldResponse")
    public String makeHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "simpleHelloWorld", targetNamespace = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/", className = "edu.pantry.pantry_webservices_jax_ws_server.SimpleHelloWorld")
    @ResponseWrapper(localName = "simpleHelloWorldResponse", targetNamespace = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/", className = "edu.pantry.pantry_webservices_jax_ws_server.SimpleHelloWorldResponse")
    @Action(input = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/HelloWorldService/simpleHelloWorldRequest", output = "http://Pantry_WebServices_JAX_WS_Server.pantry.edu/HelloWorldService/simpleHelloWorldResponse")
    public String simpleHelloWorld();

}
