package edu.pantry.pantry_HSQLDB;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
		try {
			Class.forName("org.hsqldb.jdbcDriver").newInstance();
		} catch (InstantiationException | IllegalAccessException
				| ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			Connection connexion = DriverManager.getConnection(
					"jdbc:hsqldb:file:database", "sa", "");

			Statement statement = connexion.createStatement();
			statement
					.executeUpdate("CREATE TABLE test(	Colonne1 INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,Colonne2 INT)");

			statement.executeUpdate("INSERT INTO test (Colonne2) VALUES (1)");

			ResultSet resultat = statement.executeQuery("SELECT * FROM test");

			while (resultat.next()) {
				System.out.println(resultat.getInt("Colonne2"));
			}

			// pour flusher toute la base en mémoire sur le disque

			statement.executeQuery("SHUTDOWN");
			statement.close();

			connexion.close();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		// Connection connexion =
		// DriverManager.getConnection("jdbc:hsqldb:mem:database", "sa", "");

	}
}
